### ISSUE TITLE
Add Class/Controller for Leads.

### ISSUE THREAD

**Issue by mrchrisoliver** [pipedrive/client-php#17]
Hello, 

Just noticed there's no reference to Leads in this client.

**Comment by arjan-12build** [comment]
Please implement this.

**Comment by cgarofalo** [comment]
Please implement this.

**Comment by jonathanroy** [comment]
Yes, this needs to be implemented as soon as possible.

**Comment by toxaus** [comment]
Would be great to have it

**Comment by walangitan** [comment]
There's a comment in the closed [Leads API issue](https://github.com/pipedrive/client-php/issues/39):

> We do have the Leads in the swagger config - Leads.
> Also, we will be releasing a new version of client-php in the upcoming days.

This ticket can be closed once it's include in a release?

**Comment by iget-master** [comment]
There's any release date for including the Leads? Looks like it's the core of pipedrive and is not in this official SDK. Also looks very simple to implement .

**Comment by ilyano** [comment]
I've created [PR](https://github.com/pipedrive/client-php/pull/69)
It's draft, because I've worked on 1.1.3 tag, not master branch, as I use 1.1.3 version for my current project.
Not sure, how silly my changes are, but at least code works for creating a lead. There are methods for  search, update and delete, but I haven't tested it.
