### ISSUE TITLE
PHP8.1 deprecation notices

### ISSUE THREAD

**Issue by iget-master** [pipedrive/client-php#61]
Using this package with PHP8.1 thows a lot of deprecation notices:

```
PHP Deprecated:  Return type of Pipedrive\Models\PostNote::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vendor/pipedrive/pipedrive/src/Models/PostNote.php on line 46
PHP Deprecated:  Return type of Pipedrive\Models\BaseNote::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vendor/pipedrive/pipedrive/src/Models/BaseNote.php on line 195
PHP Deprecated:  Return type of Pipedrive\Models\Person::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vendor/pipedrive/pipedrive/src/Models/Person.php on line 38
PHP Deprecated:  Return type of Pipedrive\Models\NoteCreatorUser::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vendor/pipedrive/pipedrive/src/Models/NoteCreatorUser.php on line 64
```

**Comment by elenakondrateva** [comment]
Voting this up

**Comment by teemurautiainen** [comment]
Any plans to fix these?

**Comment by adantart** [comment]
In PHP 8.1, most of the PHP internal classes are updated with tentative return types. A tentative return types means that the return types are added merely to inform the classes that extend them, and they will be enforced since PHP 9.0.

**Solution #1**
Add this line just before the "public function jsonSerialize()" of all these files:
``` 
#[\ReturnTypeWillChange]
```

**Solution #2 (I hate this one)**
Disabled E_DEPRECATED in your php.ini (or htaccess or wherever)

$ cat /etc/php/8.1/cli/php.ini | grep 'error_reporting ='
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

**Solution #3 (the desirable)**
To wait for somebody in PipeDrive team to understand  that we (the developers) are the ones promoting their tools and SaaS  using their API's (and therefore, making more money for THEM)...
That's why I prefer to use Hubspot for integrations, they act quicker.

**Comment by bilAlid** [comment]
up

**Comment by Naberal** [comment]
up

**Comment by SpaceOven** [comment]
Hi!
I tried here with the latest version (6) and I can't see these warnings anymore, so I would recommend to switch to it.
